# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='homeid',
            new_name='home',
        ),
    ]
